### ISSUE TITLE
With node version >12.9.0 pipeline fail

### ISSUE THREAD

**Issue by Danielecina** [mia-platform/api-explorer#37]
## The feauture or bug you are proposing

With node versiion > 12.9.0 pipeline build fail

Failed: https://travis-ci.com/mia-platform/api-explorer/jobs/243722744
Succeeded:  https://travis-ci.com/mia-platform/api-explorer/jobs/243452548

## The expected result for your bug

With node version > 12.9.0 pipeline build with success

### Your environment

node: 12.11.0

api-explorer: 5.8.7

os: macOS Mojave 10.14.6

**Comment by fredmaggiowski** [comment]
With node 12.13 is working, can we close this issue?

https://travis-ci.com/mia-platform/api-explorer/jobs/256945709
