### ISSUE TITLE
Textarea resizer of root params has no max

### ISSUE THREAD

**Issue by FilippoRezzonico** [mia-platform/api-explorer#88]
## The feauture or bug you are proposing
The JSONEditor textarea of root params can modify its height by using its resizer and scrolling down with it, reaching unlimited heights. Setting a max would avoid this behaviour.

**Comment by fredmaggiowski** [comment]
This is not a bug, maybe we could add a limit as a "feature" but as of now I don't see any value in it, thanks for closing the issue
